export const INITIAL_PLATFORM_TASKS = [
  {
    id: 1,
    titleKey: 'task_opening',
    subKey: 'task_opening_sub',
    type: 'checklist',
    icon: 'clipboard',
    tone: 'green',
    due: '09:30',
    done: false,
    steps: [
      'Проверить чистоту рабочей зоны',
      'Запустить и проверить оборудование',
      'Сверить температуру хранения',
      'Подготовить расходные материалы',
      'Проверить маркировку заготовок',
      'Сверить остатки упаковки',
      'Передать готовность менеджеру',
    ].map((title, index) => ({ id: index + 1, title, done: index < 4 })),
  },
  {
    id: 2,
    titleKey: 'task_temp',
    subKey: 'task_temp_sub',
    type: 'operation',
    icon: 'clock',
    tone: 'orange',
    due: '10:00',
    done: false,
  },
  {
    id: 3,
    titleKey: 'task_learn',
    subKey: 'task_learn_sub',
    type: 'learning',
    icon: 'book',
    tone: 'amber',
    due: 'Сегодня',
    done: false,
  },
  {
    id: 4,
    title: 'Проверить маркировку заготовок',
    subtitle: 'Холодильная зона • 12 позиций',
    type: 'checklist',
    icon: 'checkCircle',
    tone: 'green',
    due: '11:30',
    done: true,
  },
  {
    id: 5,
    title: 'Передать комментарий вечерней смене',
    subtitle: 'Оборудование и незакрытые вопросы',
    type: 'operation',
    icon: 'arrowSwap',
    tone: 'orange',
    due: '18:00',
    done: true,
  },
];

export const PLATFORM_NEWS = [
  {
    id: 1,
    title: 'Обновили стандарт передачи смены',
    excerpt: 'Теперь ключевые комментарии фиксируются в одном коротком чек-листе.',
    publishedAt: '2026-08-11T10:20:00+06:00',
    category: 'Процессы',
    icon: 'arrowSwap',
    tone: 'orange',
  },
  {
    id: 2,
    title: 'Новый микроурок по стандартам сервиса',
    excerpt: 'Четыре минуты, чтобы вспомнить основные шаги общения с гостем.',
    publishedAt: '2026-08-10T16:40:00+06:00',
    category: 'Обучение',
    icon: 'book',
    tone: 'amber',
  },
  {
    id: 3,
    title: 'Команда Достык закрыла месячный план',
    excerpt: 'Поздравляем коллег и делимся коротким разбором результата.',
    publishedAt: '2026-08-08T12:00:00+06:00',
    category: 'Команда',
    icon: 'users',
    tone: 'green',
  },
];

export const SUPPORT_CATEGORIES = [
  { id: 'schedule', label: 'График и смены', icon: 'calendar', tone: 'green' },
  { id: 'payroll', label: 'Зарплата', icon: 'wallet', tone: 'orange' },
  { id: 'hr', label: 'HR и документы', icon: 'briefcase', tone: 'amber' },
  { id: 'tech', label: 'Техническая проблема', icon: 'helpCircle', tone: 'neutral' },
];

export const INCOME_BREAKDOWN = [
  { key: 'base_pay', meta: '128 ч × ставка', amount: '143 200 ₸', tone: 'green', icon: 'clock' },
  { key: 'evening_pay', meta: '16 подтверждённых часов', amount: '+9 600 ₸', tone: 'orange', icon: 'moon' },
  { key: 'bonus_pay', meta: 'Качество и выполнение плана', amount: '+8 900 ₸', tone: 'amber', icon: 'checkCircle' },
  { key: 'waiting_pay', meta: '16 часов в табеле', amount: '+24 700 ₸', tone: 'neutral', icon: 'history' },
];
