import { useUiStore } from '../store/uiStore';

const copy = {
  ru: {
    platform: 'Staff Platform',
    beta: 'Новая платформа',
    today: 'Сегодня',
    shifts: 'Смены',
    income: 'Доход',
    tasks: 'Задачи',
    profile: 'Профиль',
    notifications: 'Уведомления',
    greeting_morning: 'Доброе утро',
    greeting_day: 'Добрый день',
    greeting_evening: 'Добрый вечер',
    home_sub: 'Всё важное для рабочего дня — в одном месте',
    shift_today: 'Сегодняшняя смена',
    shift_in: 'До начала смены',
    shift_started: 'Смена начата',
    start_shift: 'Начать смену',
    end_shift: 'Завершить смену',
    store: 'Торговая точка',
    role: 'Роль на смене',
    role_value: 'Сотрудник кухни',
    team_today: 'Сегодня в команде 8 человек',
    forecast: 'Прогноз дохода',
    preliminary: 'Предварительно',
    confirmed_hours: 'Подтверждено часов',
    tasks_today: 'Задачи сегодня',
    tasks_done: 'выполнено',
    quick_actions: 'Быстрые действия',
    open_schedule: 'Посмотреть график',
    swap_shift: 'Обменять смену',
    writeoff: 'Оформить списание',
    ask_help: 'Задать вопрос',
    priority: 'В фокусе',
    see_all: 'Все задачи',
    task_opening: 'Чек-лист открытия точки',
    task_opening_sub: 'Осталось 3 из 7 пунктов',
    task_temp: 'Проверить температуру кухни',
    task_temp_sub: 'Выполнить до 10:00',
    task_learn: 'Микроурок: стандарты сервиса',
    task_learn_sub: '4 минуты',
    news: 'Новости команды',
    news_title: 'Обновили стандарт передачи смены',
    news_sub: 'Ознакомьтесь до следующей смены',
    week: 'Неделя',
    month: 'Месяц',
    schedule_title: 'Мой график',
    schedule_sub: 'Смены, выходные и открытые позиции',
    upcoming: 'Ближайшие смены',
    open_shifts: 'Открытые смены',
    request_shift: 'Запросить смену',
    shift_requested: 'Запрос на смену отправлен',
    swap_requested: 'Запрос на обмен создан',
    regular_shift: 'Рабочая смена',
    day_off: 'Выходной',
    published: 'Опубликовано',
    income_title: 'Мой доход',
    income_sub: 'Понятный прогноз и официальный расчётный лист',
    month_forecast: 'Прогноз за текущий месяц',
    income_note: 'Сумма предварительная и изменится после подтверждения табеля',
    earned: 'Уже заработано',
    planned: 'План до конца месяца',
    hours: 'Часы',
    hours_confirmed: '128 подтверждено',
    additions: 'Доплаты и бонусы',
    additions_value: '+18 500 ₸',
    calculation: 'Как рассчитано',
    base_pay: 'Оплата подтверждённых смен',
    evening_pay: 'Вечерние и праздничные',
    bonus_pay: 'Подтверждённые бонусы',
    waiting_pay: 'Ожидает подтверждения',
    payslip: 'Расчётный лист',
    payslip_sub: 'Появится после закрытия расчётного периода',
    ask_income: 'Задать вопрос по начислению',
    tasks_title: 'Мои задачи',
    tasks_sub: 'Личный план, процессы точки и обучение',
    active: 'Активные',
    completed: 'Выполненные',
    all: 'Все',
    mark_done: 'Готово',
    reopen: 'Вернуть',
    operation: 'Операции',
    checklist: 'Чек-лист',
    learning: 'Обучение',
    task_completed: 'Задача выполнена',
    no_tasks: 'Здесь пока нет задач',
    no_tasks_sub: 'Новые поручения и чек-листы появятся автоматически',
    profile_title: 'Мой профиль',
    employee_id: 'ID сотрудника',
    position: 'Должность',
    position_value: 'Сотрудник ресторана',
    company_since: 'В компании',
    company_since_value: 'с июня 2025',
    hr_services: 'HR-сервисы',
    documents: 'Мои документы',
    vacation: 'Отпуск и отсутствие',
    learning_center: 'Обучение и допуски',
    services: 'Сервисы сотрудника',
    service_overview: 'Обзор',
    support: 'Помощь и обращения',
    settings: 'Настройки приложения',
    language: 'Язык',
    theme: 'Тёмная тема',
    old_system: 'Система списаний',
    old_system_sub: 'Перейти в текущую рабочую версию',
    logout: 'Выйти из аккаунта',
    coming_soon: 'Раздел готовится',
    coming_soon_sub: 'Сейчас мы собираем основу платформы. Функциональность появится в следующих обновлениях.',
    back: 'Назад',
  },
  kz: {
    platform: 'Staff Platform',
    beta: 'Жаңа платформа',
    today: 'Бүгін',
    shifts: 'Ауысымдар',
    income: 'Табыс',
    tasks: 'Тапсырмалар',
    profile: 'Профиль',
    notifications: 'Хабарламалар',
    greeting_morning: 'Қайырлы таң',
    greeting_day: 'Қайырлы күн',
    greeting_evening: 'Қайырлы кеш',
    home_sub: 'Жұмыс күніне қажетті нәрсенің бәрі бір жерде',
    shift_today: 'Бүгінгі ауысым',
    shift_in: 'Ауысым басталуына',
    shift_started: 'Ауысым басталды',
    start_shift: 'Ауысымды бастау',
    end_shift: 'Ауысымды аяқтау',
    store: 'Сауда нүктесі',
    role: 'Ауысымдағы рөл',
    role_value: 'Асүй қызметкері',
    team_today: 'Бүгін командада 8 адам',
    forecast: 'Табыс болжамы',
    preliminary: 'Алдын ала',
    confirmed_hours: 'Расталған сағаттар',
    tasks_today: 'Бүгінгі тапсырмалар',
    tasks_done: 'орындалды',
    quick_actions: 'Жылдам әрекеттер',
    open_schedule: 'Кестені көру',
    swap_shift: 'Ауысымды ауыстыру',
    writeoff: 'Есептен шығару',
    ask_help: 'Сұрақ қою',
    priority: 'Назарда',
    see_all: 'Барлық тапсырма',
    task_opening: 'Нүктені ашу чек-листі',
    task_opening_sub: '7 тармақтың 3-еуі қалды',
    task_temp: 'Асүй температурасын тексеру',
    task_temp_sub: '10:00-ге дейін орындау',
    task_learn: 'Микросабақ: сервис стандарттары',
    task_learn_sub: '4 минут',
    news: 'Команда жаңалықтары',
    news_title: 'Ауысымды тапсыру стандарты жаңартылды',
    news_sub: 'Келесі ауысымға дейін танысыңыз',
    week: 'Апта',
    month: 'Ай',
    schedule_title: 'Менің кестем',
    schedule_sub: 'Ауысымдар, демалыстар және ашық орындар',
    upcoming: 'Жақын ауысымдар',
    open_shifts: 'Ашық ауысымдар',
    request_shift: 'Ауысымды сұрау',
    shift_requested: 'Ауысымға сұрау жіберілді',
    swap_requested: 'Ауыстыру сұрауы жасалды',
    regular_shift: 'Жұмыс ауысымы',
    day_off: 'Демалыс',
    published: 'Жарияланды',
    income_title: 'Менің табысым',
    income_sub: 'Түсінікті болжам және ресми есеп парағы',
    month_forecast: 'Ағымдағы ай болжамы',
    income_note: 'Сома алдын ала және табель расталғаннан кейін өзгереді',
    earned: 'Табылғаны',
    planned: 'Ай соңына дейінгі жоспар',
    hours: 'Сағаттар',
    hours_confirmed: '128 расталды',
    additions: 'Қосымша төлемдер',
    additions_value: '+18 500 ₸',
    calculation: 'Қалай есептелді',
    base_pay: 'Расталған ауысымдар төлемі',
    evening_pay: 'Кешкі және мерекелік',
    bonus_pay: 'Расталған бонустар',
    waiting_pay: 'Растауды күтуде',
    payslip: 'Есеп айырысу парағы',
    payslip_sub: 'Есептік кезең жабылғаннан кейін пайда болады',
    ask_income: 'Есептеу туралы сұрақ қою',
    tasks_title: 'Менің тапсырмаларым',
    tasks_sub: 'Жеке жоспар, нүкте процестері және оқу',
    active: 'Белсенді',
    completed: 'Орындалған',
    all: 'Барлығы',
    mark_done: 'Дайын',
    reopen: 'Қайтару',
    operation: 'Операциялар',
    checklist: 'Чек-лист',
    learning: 'Оқу',
    task_completed: 'Тапсырма орындалды',
    no_tasks: 'Мұнда әзірге тапсырма жоқ',
    no_tasks_sub: 'Жаңа тапсырмалар мен чек-листер автоматты түрде пайда болады',
    profile_title: 'Менің профилім',
    employee_id: 'Қызметкер ID',
    position: 'Лауазым',
    position_value: 'Мейрамхана қызметкері',
    company_since: 'Компанияда',
    company_since_value: '2025 жылғы маусымнан',
    hr_services: 'HR-сервистер',
    documents: 'Менің құжаттарым',
    vacation: 'Демалыс және болмау',
    learning_center: 'Оқу және рұқсаттар',
    services: 'Қызметкер сервистері',
    service_overview: 'Шолу',
    support: 'Көмек және өтініштер',
    settings: 'Қолданба баптаулары',
    language: 'Тіл',
    theme: 'Қараңғы тақырып',
    old_system: 'Есептен шығару жүйесі',
    old_system_sub: 'Қазіргі жұмыс нұсқасына өту',
    logout: 'Аккаунттан шығу',
    coming_soon: 'Бөлім дайындалуда',
    coming_soon_sub: 'Қазір платформаның негізін жинап жатырмыз. Функционал келесі жаңартуларда пайда болады.',
    back: 'Артқа',
  },
};

export function usePlatformCopy() {
  const lang = useUiStore((s) => s.lang);
  return { p: copy[lang] || copy.ru, lang };
}
