import Foundation

// Двуязычные строки (RU/KZ). Доступ через AppSettings.t("key").
enum Strings {
    static let ru: [String: String] = [
        "app_name": "Списания",
        "login_title": "Вход в систему",
        "login_sub": "Учёт списаний продукции Bahandi",
        "login_login": "Логин",
        "login_pass": "Пароль",
        "login_ph_login": "Введите логин",
        "login_btn": "Войти",
        "login_demo": "демо-доступ",
        "login_error": "Неверный логин или пароль",
        "role_sender": "Отправитель",
        "role_reviewer": "Проверяющий",
        "role_admin": "Администратор",
        "greeting": "Здравствуйте,",
        "create_cta": "Создать списание",
        "create_cta_sub": "Оформить новую заявку за минуту",
        "recent": "Последние заявки",
        "see_all": "Все заявки",
        "nav_home": "Главная",
        "nav_create": "Создать",
        "nav_my": "Заявки",
        "nav_profile": "Профиль",
        "nav_queue": "Очередь",
        "nav_history": "История",
        "nav_admin": "Управление",
        "st_pending": "На проверке",
        "st_approved": "Подтверждена",
        "st_rejected": "Отклонена",
        "st_approved_s": "Подтверждены",
        "st_rejected_s": "Отклонены",
        "tab_all": "Все",
        "type_hold": "С удержанием",
        "type_nohold": "Без удержания",
        "type_hold_sub": "Сумма удерживается с сотрудника",
        "type_nohold_sub": "Списание за счёт точки",
        "step_photo": "Фото продукции",
        "step_photo_h": "Сфотографируйте списываемый товар — минимум одно фото",
        "step_point": "Торговая точка",
        "step_point_h": "Выберите точку, где оформляется списание",
        "step_type": "Тип списания",
        "step_type_h": "Удерживать ли сумму с сотрудника",
        "step_emp": "Сотрудник",
        "step_emp_h": "С кого удержать сумму списания",
        "step_comment": "Комментарий",
        "step_comment_h": "Опишите причину списания, минимум 10 символов",
        "take_photo": "Сделать фото",
        "from_gallery": "Из галереи",
        "uploading": "Загрузка…",
        "search_emp": "Поиск сотрудника",
        "comment_ph": "Например: товар с истёкшим сроком годности…",
        "comment_need": "Минимум 10 символов",
        "comment_ok": "Готово к отправке",
        "summary": "Сводка по заявке",
        "f_point": "Точка",
        "f_type": "Тип",
        "f_emp": "Сотрудник",
        "f_photos": "Фото",
        "f_comment": "Комментарий",
        "f_id": "ID",
        "step": "Шаг",
        "next": "Далее",
        "back": "Назад",
        "submit": "Отправить на проверку",
        "empty_title": "Заявок пока нет",
        "empty_sub": "Создайте первое списание — это займёт минуту",
        "reject_reason": "Причина отклонения",
        "timeline": "История заявки",
        "tl_created": "Заявка создана",
        "tl_review": "Передана на проверку",
        "tl_approved": "Подтверждена",
        "tl_rejected": "Отклонена",
        "tl_iiko": "Акт создан в iiko",
        "tl_pending": "Ожидает решения проверяющего",
        "queue_count": "Ожидают проверки",
        "queue_empty": "Очередь пуста",
        "queue_empty_sub": "Все заявки обработаны",
        "author_label": "Отправитель",
        "iiko_done": "Акт списания создан в iiko",
        "iiko_done_sub": "Интеграция выполнена автоматически",
        "iiko_will": "После подтверждения акт уйдёт в iiko",
        "approve": "Подтвердить",
        "reject": "Отклонить",
        "approve_title": "Подтвердить списание?",
        "approve_body": "Заявка будет одобрена, отправитель получит уведомление.",
        "reject_title": "Отклонить заявку",
        "reject_body": "Укажите причину — она вернётся отправителю",
        "reject_ph": "Причина отклонения…",
        "cancel": "Отмена",
        "settings": "Настройки",
        "language": "Язык",
        "theme": "Тема",
        "theme_system": "Система",
        "theme_light": "Светлая",
        "theme_dark": "Тёмная",
        "logout": "Выйти",
        "sent_toast": "Заявка отправлена на проверку",
        "approved_toast": "Заявка подтверждена · акт в iiko",
        "rejected_toast": "Заявка отклонена",
        "error_generic": "Что-то пошло не так",
        "admin_users": "Пользователи",
        "admin_stores": "Точки",
        "admin_employees": "Сотрудники",
        "admin_add": "Добавить",
        "save": "Сохранить",
        "create": "Создать",
        "f_fullname": "ФИО",
        "f_username": "Логин",
        "f_password": "Пароль",
        "f_role": "Роль",
        "f_email": "Email",
        "f_address": "Адрес",
        "f_position": "Должность",
        "f_name": "Название",
        "no_store": "Без точки",
        "admin_active": "Активен",
        "ai_title": "ИИ распознал на фото",
        "ai_writeoff": "Обнаружена испорченная/повреждённая продукция — рекомендуется списание. Причина подставлена в комментарий.",
        "ai_ok": "Явных признаков порчи не обнаружено. Решение остаётся за вами.",
        "ai_state_spoiled": "испорчен",
        "ai_state_defect": "повреждён",
        "ai_state_good": "годен",
    ]

    static let kz: [String: String] = [
        "app_name": "Есептен шығару",
        "login_title": "Жүйеге кіру",
        "login_sub": "Bahandi өнімдерін есептен шығару",
        "login_login": "Логин",
        "login_pass": "Құпиясөз",
        "login_ph_login": "Логинді енгізіңіз",
        "login_btn": "Кіру",
        "login_demo": "демо-қолжетімділік",
        "login_error": "Логин немесе құпиясөз қате",
        "role_sender": "Жіберуші",
        "role_reviewer": "Тексеруші",
        "role_admin": "Әкімші",
        "greeting": "Сәлеметсіз бе,",
        "create_cta": "Есептен шығару",
        "create_cta_sub": "Жаңа өтінімді бір минутта рәсімдеңіз",
        "recent": "Соңғы өтінімдер",
        "see_all": "Барлығы",
        "nav_home": "Басты бет",
        "nav_create": "Жасау",
        "nav_my": "Өтінімдер",
        "nav_profile": "Профиль",
        "nav_queue": "Кезек",
        "nav_history": "Тарих",
        "nav_admin": "Басқару",
        "st_pending": "Тексеруде",
        "st_approved": "Расталған",
        "st_rejected": "Қабылданбады",
        "st_approved_s": "Расталған",
        "st_rejected_s": "Қабылданбады",
        "tab_all": "Барлығы",
        "type_hold": "Ұстаумен",
        "type_nohold": "Ұстаусыз",
        "type_hold_sub": "Сома қызметкерден ұсталады",
        "type_nohold_sub": "Нүкте есебінен есептен шығару",
        "step_photo": "Өнім фотосы",
        "step_photo_h": "Тауарды суретке түсіріңіз — кемінде бір фото",
        "step_point": "Сауда нүктесі",
        "step_point_h": "Нүктені таңдаңыз",
        "step_type": "Есептен шығару түрі",
        "step_type_h": "Соманы қызметкерден ұстау керек пе",
        "step_emp": "Қызметкер",
        "step_emp_h": "Сома кімнен ұсталады",
        "step_comment": "Түсініктеме",
        "step_comment_h": "Себебін сипаттаңыз, кемінде 10 таңба",
        "take_photo": "Фото түсіру",
        "from_gallery": "Галереядан",
        "uploading": "Жүктелуде…",
        "search_emp": "Қызметкерді іздеу",
        "comment_ph": "Мысалы: жарамдылық мерзімі өткен тауар…",
        "comment_need": "Кемінде 10 таңба",
        "comment_ok": "Жіберуге дайын",
        "summary": "Өтінім қорытындысы",
        "f_point": "Нүкте",
        "f_type": "Түрі",
        "f_emp": "Қызметкер",
        "f_photos": "Фото",
        "f_comment": "Түсініктеме",
        "f_id": "ID",
        "step": "Қадам",
        "next": "Әрі қарай",
        "back": "Артқа",
        "submit": "Тексеруге жіберу",
        "empty_title": "Әзірге өтінім жоқ",
        "empty_sub": "Алғашқы есептен шығаруды жасаңыз",
        "reject_reason": "Қабылдамау себебі",
        "timeline": "Өтінім тарихы",
        "tl_created": "Өтінім жасалды",
        "tl_review": "Тексеруге берілді",
        "tl_approved": "Расталды",
        "tl_rejected": "Қабылданбады",
        "tl_iiko": "iiko-да акт жасалды",
        "tl_pending": "Шешімді күтуде",
        "queue_count": "Тексеруді күтуде",
        "queue_empty": "Кезек бос",
        "queue_empty_sub": "Барлық өтінім өңделді",
        "author_label": "Жіберуші",
        "iiko_done": "Есептен шығару актісі iiko-да жасалды",
        "iiko_done_sub": "Интеграция автоматты орындалды",
        "iiko_will": "Растағаннан кейін акт iiko-ға жіберіледі",
        "approve": "Растау",
        "reject": "Қабылдамау",
        "approve_title": "Есептен шығаруды растайсыз ба?",
        "approve_body": "Өтінім мақұлданады, жіберуші хабарлама алады.",
        "reject_title": "Өтінімді қабылдамау",
        "reject_body": "Себебін көрсетіңіз — ол жіберушіге қайтады",
        "reject_ph": "Қабылдамау себебі…",
        "cancel": "Болдырмау",
        "settings": "Баптаулар",
        "language": "Тіл",
        "theme": "Тақырып",
        "theme_system": "Жүйе",
        "theme_light": "Ашық",
        "theme_dark": "Қараңғы",
        "logout": "Шығу",
        "sent_toast": "Өтінім тексеруге жіберілді",
        "approved_toast": "Өтінім расталды · акт iiko-да",
        "rejected_toast": "Өтінім қабылданбады",
        "error_generic": "Бірдеңе дұрыс болмады",
        "admin_users": "Пайдаланушылар",
        "admin_stores": "Нүктелер",
        "admin_employees": "Қызметкерлер",
        "admin_add": "Қосу",
        "save": "Сақтау",
        "create": "Құру",
        "f_fullname": "Аты-жөні",
        "f_username": "Логин",
        "f_password": "Құпиясөз",
        "f_role": "Рөл",
        "f_email": "Email",
        "f_address": "Мекенжай",
        "f_position": "Лауазым",
        "f_name": "Атауы",
        "no_store": "Нүктесіз",
        "admin_active": "Белсенді",
        "ai_title": "ЖИ фотодан анықтады",
        "ai_writeoff": "Бүлінген/зақымдалған өнім анықталды — есептен шығару ұсынылады. Себеп түсініктемеге қойылды.",
        "ai_ok": "Бүліну белгілері анықталмады. Шешім сізде.",
        "ai_state_spoiled": "бүлінген",
        "ai_state_defect": "зақымдалған",
        "ai_state_good": "жарамды",
    ]
}
